### ISSUE TITLE
No option to set password when manually registering using public key.

### ISSUE THREAD

**Issue by HendrikPetertje** [ssbc/go-ssb-room#234]
When the users on my room try to sign up to connect and doing so manually (Patchwork and the likes) there isn't a password field with the SSB public key field. 

![image](https://user-images.githubusercontent.com/3583395/120224589-073dfe00-c244-11eb-9c9e-85e044407ac5.png)

Because of this users need to reach out to server admins to send them password reset links.

**Comment by staltz** [comment]
I guess it could be an additional page after you submit the ID.

**Comment by decentral1se** [comment]
I think I can get a fix in for this.
