### ISSUE TITLE
Docker deployment

### ISSUE THREAD

**Issue by mat-l** [ssbc/go-ssb-room#237]
Thank you for the great work 🙏🏽

Instead of installing all dependencies manually, I would prefer a Docker based set up for Rooms 2.0 to host an instance by myself. Are you planning to publish a container?

**Comment by cryptix** [comment]
@HendrikPetertje is already working on one. I hope he will share it. :)

**Comment by cryptix** [comment]
Ok, I couldn't help but scratch the itch.

I added a pretty decent  Dockerfile (it uses two different containers for building and running the server such that the toolchain doesn't end up in the final image) in #239 but I'm a bit blank on best practice with adding nginx or similar as a reverse proxy for TLS (see docs/deployment in this repo). I suppose one would use docker-compose for that?

You can try it with these steps:

```bash
git clone https://github.com/ssb-ngi-pointer/go-ssb-room
cd go-ssb-room
git checkout try-docker
docker build -t ssb-ngi-pointer/go-ssb-room .
docker run ssb-ngi-pointer/go-ssb-room /server -https-domain foo.com
```

**Comment by HendrikPetertje** [comment]
> Ok, I couldn't help but scratch the itch.


Understandable ;)

I put up a pull request with a docker + docker-compose construction. feel free to pick stuff from it for your own config if you think it helps (you probably don't want all of it which is fine ;) )

**Comment by mat-l** [comment]
Nice, will check it the next days 😊
Thanks for fast feedback.

**Comment by ahdinosaur** [comment]
by the way, `@3wordchant` has a Dockerfile for their coopcloud.tech deploy: https://git.autonomic.zone/3wordchant/docker-go-ssb-room/, looks really good. also has a corresponding compose.yml: https://git.autonomic.zone/3wordchant/docker-go-ssb-room

**Comment by decentral1se** [comment]
Following https://github.com/ssb-ngi-pointer/go-ssb-room/issues/237#issuecomment-854249384, https://git.coopcloud.tech/coop-cloud/go-ssb-room is now running https://butt.autonomic.zone :tada:  We'll be maintaining that as we go. If anyone is up for co-maintaining / testing, please do [let us know](https://docs.coopcloud.tech/intro/contact/).

**Comment by decentral1se** [comment]
Several options for this already, think this can be closed. Think https://github.com/ssbc/go-ssb-room/issues/309 can improve the situation but for Another Day :tm:
