### ISSUE TITLE
Getting Started Hurdles -- Connecting my admin users manyverse client to the room...

### ISSUE THREAD

**Issue by ph1l** [ssbc/go-ssb-room#280]
Hey devs~

I've got a service up and running via the deb package and added a user from a dev compiled insert_user cmd off server, but now it's not clear to me how to connect my client manyverse to the "room." I tried pasting the https invite url into manyverse, but it gets "rejected."

Following the https link in firefox keeps giving me a "Unable to connect" error. I don't see any errors in the webserver or go-ssb-room service log.

:-/

**Comment by staltz** [comment]
Try again the invite link a couple of times with Firefox or Chrome, and if it still has problems, create new invites.

The "paste" workflow is indeed not supported in Manyverse but we have an issue open to add support for that, even though clicking the link is much better/easier.
