### ISSUE TITLE
Yunohost install: which credentials at first login?

### ISSUE THREAD

**Issue by xegulon** [ssbc/go-ssb-room#300]
I installed the app on my Yunohost server. In the yunohost installation interface, I had to enter a password and an admin id. When I visit the app, I can't manage to connect to it for the first time. I tried the credentials `admin` and the password I setup in the Yunohost interface, but it doesn't work. So what credentials should I use for the first time?
Thanks.

**Comment by decentral1se** [comment]
@xegulon it probably makes more sense to raise this ticket on https://github.com/YunoHost-Apps/ssbroom_ynh?

https://github.com/ssb-ngi-pointer/go-ssb-room/blob/master/docs/deployment.md#first-admin-user might be helpful.

**Comment by mhfowler** [comment]
thanks @decentral1se. hi @xegulon, you should be able to log in using the admin_id you entered (should be a valid ssb public key like @5Pt3dKy2HTJ0mWuS78oIiklIX0gBz6BTfEnXsbvke9c=.ed25519) with whatever password you entered while installing the app on yunohost

**Comment by xegulon** [comment]
Ok thanks I'll try that

**Comment by decentral1se** [comment]
Assuming this got resolved, please re-open if not the case :+1:
