### ISSUE TITLE
Maintainers group?

### ISSUE THREAD

**Issue by decentral1se** [ssbc/go-ssb-room#313]
Is there something setup? Shall we set something up? I'd be happy to herd some cats on this one.

**Comment by decentral1se** [comment]
Ah, sorry if not clear: people who maintain this software.

For example, I have some PRs lingering and I don't know who to ask to get them reviewed/merged. There are some tickets I'd like to push along like https://github.com/ssbc/go-ssb-room/issues/309 but who do I ask? And who gets to make decisions about what is done with this repository?

Things like that. I mentioned some of this on ssb also but didn't see any obvious next steps.

**Comment by staltz** [comment]
@decentral1se Currently the members consist of `@staltz`, `@mixmix`, `@arj03`, `@cryptix`, `@clehner`, and `@mycognosist`. Any of the members can review PRs, merge PRs, and publish new versions of libraries, and manage the ssbc org. Rules for becoming a member are: https://github.com/ssbc/.github/blob/master/MEMBERSHIP.md

You have some great PRs and issues in this repo but I personally don't have time at the moment to review, merge, publish. I am insanely swamped with things to do. You can try asking others and if you're on a tight schedule, for the time being you can publish commits on a fork and use the fork.

**Comment by decentral1se** [comment]
OK i'll just wait for someone to turn up. Good luck everyone with All The Things.
