### ISSUE TITLE
I haven't code invitations form ather friends

### ISSUE THREAD

**Issue by Ahmednabawy1987** [ssbc/go-ssb-room#314]

**Comment by Ahmednabawy1987** [comment]
I want to learn how to hacking up another person mobile

**Comment by decentral1se** [comment]
Hi @Ahmednabawy1987, could you please explain more about what you're having trouble with?

**Comment by Ahmednabawy1987** [comment]
I want invitation code of ssb room

**Comment by Ahmednabawy1987** [comment]
I want invtation code of Manyverse program

**Comment by decentral1se** [comment]
@Ahmednabawy1987 I would recommend watching https://www.youtube.com/watch?v=W5p0y_MWwDE and reading https://www.manyver.se/faq/connect-room. Hope that works out for you :+1:
