### ISSUE TITLE
php version ???

### ISSUE THREAD

**Issue by rocky-III** [ssbc/go-ssb-room#319]
would it be possible to write a php version of ssh-room?

**Comment by staltz** [comment]
Yes

**Comment by rocky-III** [comment]
does this version already exist? If not, What does it take to write on? 

A php version could be installed on any regular Shard host Webserver.

**Comment by rocky-III** [comment]
Ohhh...  `closed this as not planned`

**Comment by staltz** [comment]
I meant that it's possible, I didn't say I plan to build it. Someone who knows PHP well could build it.

**Comment by rocky-III** [comment]
if i find someone who knows php well - would there be a chance to get the needed work funded?

**Comment by rocky-III** [comment]
@staltz maybe you want to reopen this issue. I find it important that everybody can host a server app with a minimum of effort. PHP offers here a lot of advantages over GO.

Maybe there is someone in the community who can do the job in PHP.   What do you think?

**Comment by staltz** [comment]
@rocky-III this is not an "issue" about go-ssb-room, this is just an idea you want to build.

**Comment by rocky-III** [comment]
@staltz it´s in issue in that scene that if the app would be available in php it would be much easier to spread. I can´t do this in PHP - i can´t build it... but the community should think about it. Let the discuss this and reopen the issue - of find an other place to discuss it...
