### ISSUE TITLE
Documentation - manually generate dhparams

### ISSUE THREAD

**Issue by KyleMaas** [ssbc/go-ssb-room#324]
Following through the installation docs (which are quite good, I might add) on an Ubuntu 22.04.1 server, there's one issue I ran into that I think might be worth mentioning.  certbot did not generate a dhparams file.  Maybe add an example command for generating that?  Something like:

```openssl dhparam -out /etc/letsencrypt/ssl-dhparams.pem 2048```

**Comment by decentral1se** [comment]
Nice @KyleMaas, PRs welcome!
