### ISSUE TITLE
Error installing peachbot-go-sbot on yunohost

### ISSUE THREAD

**Issue by noccio** [ssbc/go-ssb-room#325]
I send a request on yunohost forum on https://forum.yunohost.org/t/error-installing-peachbot/21735

I cannot install peachbot-go-sbot because of this error

`
Info: [################+...] > Starting a systemd service...

Info: The service peachpub-peach-web.service has correctly executed the action start.

Warning: (this may take some time)

Warning: The service peachpub-go-sbot.service didn't fully executed the action start before the timeout.

Warning: Please find here an extract of the end of the log of the service peachpub-go-sbot.service:

Warning: Oct 19 10:16:51 systemd[1]: peachpub-go-sbot.service: Scheduled restart job, restart counter is at 2.

Warning: Oct 19 10:16:51 systemd[1]: Stopped go-sbot service.

Warning: Oct 19 10:16:51 systemd[1]: Started go-sbot service.

Warning: Oct 19 10:16:51 systemd[1]: peachpub-go-sbot.service: Main process exited, code=exited, status=1/FAILURE

Warning: Oct 19 10:16:51 systemd[1]: peachpub-go-sbot.service: Failed with result 'exit-code'.

Warning: Oct 19 10:16:51 systemd[1]: peachpub-go-sbot.service: Scheduled restart job, restart counter is at 3.

Warning: Oct 19 10:16:51 systemd[1]: Stopped go-sbot service.

Warning: Oct 19 10:16:51 systemd[1]: Started go-sbot service.

Warning: Oct 19 10:16:51 systemd[1]: peachpub-go-sbot.service: Main process exited, code=exited, status=1/FAILURE

Warning: Oct 19 10:16:51 systemd[1]: peachpub-go-sbot.service: Failed with result 'exit-code'.

Warning: Oct 19 10:16:52 systemd[1]: peachpub-go-sbot.service: Scheduled restart job, restart counter is at 4.

Warning: Oct 19 10:16:52 systemd[1]: Stopped go-sbot service.

Warning: Oct 19 10:16:52 systemd[1]: Started go-sbot service.

Warning: Oct 19 10:16:52 systemd[1]: peachpub-go-sbot.service: Main process exited, code=exited, status=1/FAILURE

Warning: Oct 19 10:16:52 systemd[1]: peachpub-go-sbot.service: Failed with result 'exit-code'.

Warning: Oct 19 10:16:52 systemd[1]: peachpub-go-sbot.service: Scheduled restart job, restart counter is at 5.

Warning: Oct 19 10:16:52 systemd[1]: Stopped go-sbot service.

Warning: Oct 19 10:16:52 systemd[1]: peachpub-go-sbot.service: Start request repeated too quickly.

Warning: Oct 19 10:16:52 systemd[1]: peachpub-go-sbot.service: Failed with result 'exit-code'.

Warning: Oct 19 10:16:52 systemd[1]: Failed to start go-sbot service.

Warning: \-\-\-

Warning: github.com/dgraph-io/ristretto/z.OpenMmapFile

Warning:        /home/rust/go/pkg/mod/github.com/dgraph-io/ristretto@v0.0.4-0.20210122082011-bb5d392ed82d/z/file.go:86

Warning: github.com/dgraph-io/badger/v3.(*logFile).open

Warning:        /home/rust/go/pkg/mod/github.com/dgraph-io/badger/v3@v3.2011.1/memtable.go:556

Warning: github.com/dgraph-io/badger/v3.(*valueLog).open

Warning:        /home/rust/go/pkg/mod/github.com/dgraph-io/badger/v3@v3.2011.1/value.go:581

Warning: github.com/dgraph-io/badger/v3.Open

Warning:        /home/rust/go/pkg/mod/github.com/dgraph-io/badger/v3@v3.2011.1/db.go:334

Warning: go.cryptoscope.co/ssb/repo.OpenBadgerDB

Warning:        /srv/peachcloud/automation/go-ssb/repo/multilogs.go:39

Warning: go.cryptoscope.co/ssb/sbot.New

Warning:        /srv/peachcloud/automation/go-ssb/sbot/new.go:291

Warning: main.runSbot

Warning:        /srv/peachcloud/automation/go-ssb/cmd/go-sbot/main.go:336

Warning: main.main

Warning:        /srv/peachcloud/automation/go-ssb/cmd/go-sbot/main.go:511

Warning: runtime.main

Warning:        /srv/peachcloud/automation/install-go/go/src/runtime/proc.go:225

Warning: runtime.goexit

Warning:        /srv/peachcloud/automation/install-go/go/src/runtime/asm_arm.s:841

Warning: whoami failed: Io { source: Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }, context: "failed to initiate tcp stream connection" }

Warning: whoami failed: Io { source: Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }, context: "failed to initiate tcp stream connection" }

Warning: whoami failed: Io { source: Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }, context: "failed to initiate tcp stream connection" }

Warning: whoami failed: Io { source: Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }, context: "failed to initiate tcp stream connection" }

Warning: whoami failed: Io { source: Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }, context: "failed to initiate tcp stream connection" }

Warning: whoami failed: Io { source: Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }, context: "failed to initiate tcp stream connection" }

Warning: whoami failed: Io { source: Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }, context: "failed to initiate tcp stream connection" }

Warning: whoami failed: Io { source: Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }, context: "failed to initiate tcp stream connection" }

Warning: whoami failed: Io { source: Os { code: 111, kind: ConnectionRefused, message: "Connection 
refused" }, context: "failed to initiate tcp stream connection" }

Warning: whoami failed: Io { source: Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }, context: "failed to initiate tcp stream connection" }

Warning: [2022-10-19T08:22:14Z ERROR peach_config] peach-config did not successfully connect to sbot: Failed to find sbot_id after 10 attempts

Warning: [2022-10-19T08:22:14Z ERROR peach_config] peach-config encountered an error during publish address: Error in golgi: IO error: failed to initiate tcp stream connection
`

**Comment by decentral1se** [comment]
Hey @noccio :wave: Probably better to raise an issue on https://github.com/YunoHost-Apps/ssbroom_ynh? /cc @mycognosist @mhfowler

**Comment by mycognosist** [comment]
Hi @noccio, I believe the best place to raise this is in the https://github.com/YunoHost-Apps/peachpub_ynh repo. @mhfowler has been on holiday but I'm sure they'll respond in due course.

Thanks for the ping, @decentral1se.

**Comment by noccio** [comment]
Thanks @mycognosist and @decentral1se for the input, I opened the issue in https://github.com/YunoHost-Apps/peachpub_ynh/issues/22

**Comment by decentral1se** [comment]
Good hustle folks, guess we can close this one off :100:
