### ISSUE TITLE
Include insert-user binary in the Debian package

### ISSUE THREAD

**Issue by KyleMaas** [ssbc/go-ssb-room#327]
Considering you need the insert-user program to actually start using go-ssb-room, it would be nice if a compiled version of that was included in the Debian package.

**Comment by decentral1se** [comment]
Was underway in https://github.com/ssbc/go-ssb-room/pull/266 but needs picking up again...

This is a dupe of https://github.com/ssbc/go-ssb-room/issues/241?

**Comment by KyleMaas** [comment]
Yep, I'd say so.
