### ISSUE TITLE
Migrate to new ssbc urls

### ISSUE THREAD

**Issue by decentral1se** [ssbc/go-ssb-room#332]
Similarly to https://github.com/ssbc/go-ssb/issues/160 (collectively managed repos)

**Comment by macornwell** [comment]
From a person pulling down the code and trying to build, the build no longer works.

`build github.com/ssb-ngi-pointer/go-ssb-room/v2/cmd/insert-user: cannot load embed: malformed module path "embed": missing dot in first path element`

**Comment by decentral1se** [comment]
@macornwell can you open up a new issue for your build error with more details? I think it might be unrelated to this urls thing. I can build on latest with Go 18.3.
