### ISSUE TITLE
Document shscap option

### ISSUE THREAD

**Issue by stevenroose** [ssbc/go-ssb-room#335]
So when installing, I found the shscap option which is called `appKey` in the code. This led me to assume it's a secret and thus I should change it to another value. Lost without documentation, I just created a random 32-byte base64 key and put it in there.

After debugging for a few weeks, I noticed that my setup works if I remove my shscap option..

So what is the option intended for (other than being [juicy](https://github.com/ssbc/go-ssb-room/blob/master/cmd/server/main.go#L74)) and why does it seem like it needs to be set to `1KHLiKZvAvjbY1ziZEHMXawbCEIM6qwjCDm3VYRan/s=` in order to work?

**Comment by decentral1se** [comment]
> After debugging for a few weeks

:grimacing: 

> So what is the option intended for (other than being [juicy](https://github.com/ssbc/go-ssb-room/blob/master/cmd/server/main.go#L74)) and why does it seem like it needs to be set to 1KHLiKZvAvjbY1ziZEHMXawbCEIM6qwjCDm3VYRan/s= in order to work?

https://github.com/ssbc/go-ssb-room/issues/316#issuecomment-1294878528

> Lost without documentation

Yeh, definitely needs some documentation alright.

**Comment by stevenroose** [comment]
@decentral1se is this sufficient? https://github.com/ssbc/go-ssb-room/pull/346
