### ISSUE TITLE
How to generate a multiserver address?

### ISSUE THREAD

**Issue by KyleMaas** [ssbc/go-ssb-room#342]
How would I generate a multiserver address for connecting to a room from clients which don't have ssb-http-invite-client support, for example @HendrikPetertje did here:

https://picoroom.hendrikpeter.net/

**Comment by decentral1se** [comment]
Good question! https://github.com/ssbc/multiserver#address-format might be a handy reference to start with...

**Comment by KyleMaas** [comment]
How do you get `go-ssb-room` to generate a non-HTTP open invite code to even be able to put it in that format?  Could the "Create new invite" screen generate a multiserver address?  How do you create a multiple-use invite code in `go-ssb-room`?

**Comment by staltz** [comment]
> How do you get `go-ssb-room` to generate a non-HTTP open invite code to even be able to put it in that format?

Take the multiserver address for the room and suffix it with a specific magic string, see: https://github.com/ssbc/ssb-room-client/blob/0815665f58949b7795f2308ca9757cc4f638f50a/src/utils.ts#L20

**Comment by staltz** [comment]
The multiserver address is `net:$HOST:$PORT~shs:$BASE64_OF_SSB_ID`.

**Comment by KyleMaas** [comment]
Is there any way to disable anonymous invites with the magic string, or is it just relying on ordinary people not knowing that exists?

**Comment by staltz** [comment]
go-ssb-room has 3 modes: open, community, restricted. Magic code invites only work for open mode. Or in community mode only if the invite claimer has been manually added as a member.

**Comment by KyleMaas** [comment]
That makes sense.  Thanks!
