### ISSUE TITLE
are aliases supposed to allow connecting to a user? - they don't seem to

### ISSUE THREAD

**Issue by stevenroose** [ssbc/go-ssb-room#347]
From the [room 2.0 video in the readme of this project](https://www.youtube.com/watch?v=W5p0y_MWwDE), I seem to understand that someone that has my alias URL should upon clicking be able to connect to me through the room? Is that correct?

I tried this while the aliased client was online on the room, and the consuming client (both Manyverse) opened the alias link, it said "user not online" and the server reports this
```
level=warn unit=tunnel caller=<@dloB.ed25519> target=<@384p.ed25519> event="source errored" err="muxrpc CallError: Error - client is a stranger"
```

the `client is a stranger` seems to suggest that strangers can't open alias links? (my room is in community mode)

**Comment by decentral1se** [comment]
According to https://ssbc.github.io/rooms2/#alias :point_down: 

> [Internal users](https://ssbc.github.io/rooms2/#internal-user) and [external users](https://ssbc.github.io/rooms2/#external-user) who visit a target user's [alias endpoint](https://ssbc.github.io/rooms2/#web-endpoint) can [consume it](https://ssbc.github.io/rooms2/#alias-consumption) in order to [connect](https://ssbc.github.io/rooms2/#tunneled-connection) with the target internal user

Is this perhaps a Manyverse firewall issue? e.g. https://gitlab.com/staltz/manyverse/-/issues/1808

**Comment by staltz** [comment]
Yes, by default manyverse has a firewall `ssb-conn-firewall` that renders aliases... kind of useless. But the firewall can be disabled in Settings

**Comment by stevenroose** [comment]
I have the firewall disabled and it still doesn't work.

But ok, that's a really cool feature, will the alias-consuming peer keep the connection attached to me? Like will it keep being able to connect with me over the server? Or is the connection one-time-use?

This would be really cool with an additional feature allowing someone to automatically add a friend to the server and that the connection would then turn into a full member connection automatically.

So that the flow becomes

- I send alias
- they connect through alias
- I notice it's them, in Manyverse press them and select "invite/add to server" (community mode)
- server adds their ID so that the connection they have with server is not a connection like one of a regular member
- they become visible to other members of the server

If this flow would work, that would be amazing!

**Comment by staltz** [comment]
> Like will it keep being able to connect with me over the server?

If you're using `ssb-room-client`, yes it will: https://github.com/ssbc/ssb-room-client/blob/0815665f58949b7795f2308ca9757cc4f638f50a/src/plugin-room-client.ts#L159-L161



> If this flow would work, that would be amazing!

Sounds similar to a flow I've been sketching called broker auth: https://staltz.github.io/ssb-room-broker-auth-spec/

**Comment by decentral1se** [comment]
> I have the firewall disabled and it still doesn't work.

Darn. Can anyone else confirm / reproduce that this isn't working? Sounding like a bug now to me :thinking:

**Comment by stevenroose** [comment]
> If you're using ssb-room-client, yes it will

I'm using Manyverse..

> Sounds similar to a flow I've been sketching called broker auth: ...

Nice! I can only encourage the development! If there is anything I can do to help like debugging, let me know. I don't have any JS/TS experience, but I do have Go experience.

**Comment by stevenroose** [comment]
Are alias connects supposed to work in "community" mode?

**Comment by staltz** [comment]
> Are alias connects supposed to work in "community" mode?

Yes

**Comment by stevenroose** [comment]
I just flipped the firewall switch twice, on and off again, and it works now. That's definitely a Manyverse bug and not a bug here.

**Comment by stevenroose** [comment]
Reported here: https://gitlab.com/staltz/manyverse/-/issues/2122
