### ISSUE TITLE
error when building the development server

### ISSUE THREAD

**Issue by chereseeriepa** [ssbc/go-ssb-room#352]
Im getting an error that is preventing me from building the development server. When I run:
```
cd cmd/server
go build -tags dev
```

Im getting the following error:
```
# github.com/ssbc/go-secretstream/secrethandshake
../../../../go/pkg/mod/github.com/ssbc/go-secretstream@v1.2.11-0.20221019175226-fa042d4912fe/secrethandshake/string.go:21:24: cannot use s.appKey (variable of type [32]byte) as type []byte in argument to hex.Encode
```

NOTE: I only received this error yesterday upon pulling in the latest changes from master in the past 5 days or so.

**Comment by decentral1se** [comment]
@chereseeriepa Opened up https://github.com/ssbc/go-secretstream/pull/21 https://github.com/ssbc/go-ssb-room/pull/353 to fix + help catch in the CI before breaking dev workflows. Hoping someone might review shortly, will merge later on tomorrow if now. If you need to move fast, you can see the fixing patch inhttps://github.com/ssbc/go-secretstream/pull/21 (and docs on how to load that into the build / `go.mod` in https://github.com/ssbc/go-ssb#building) :+1:

**Comment by decentral1se** [comment]
Should be fixed now, thanks for the report :heart_decoration:
