### ISSUE TITLE
Info on how to access the admin page 

### ISSUE THREAD

**Issue by ThomasFreedman** [ssbc/go-ssb-room#363]
I installed the ssbroom app on yunohost, but can't see any link or way to get to admin pages of room.

I did add a sbb id when I installed it, but don't know how to use manyverse to connect to the room.

There are no yunohost docs despite the link on sbbroom github pages.

I installed to allow anonymous users, presumably that means public. I see your admonition for a "full domain name" but not sure what that means. Does that imply you can't change the URL for the app to be something besides the domain's root?

**Comment by ThomasFreedman** [comment]
I confirmed that is the cause, ssbrooms must be accessed from the domain root, it fails if yo change the url to something below the root or presumably is using a subdomain,

**Comment by ThomasFreedman** [comment]
Consider changing the text to make this more clear than simply saying "full doman". Suggestion: root of the domain such as https://maindomain.tld/

**Comment by decentral1se** [comment]
Thanks for the report @ThomasFreedman! /cc @mhfowler as YunoHost hacker in residence for `go-ssb-room` (I think!)
