### ISSUE TITLE
Cannot sign in with SSB

### ISSUE THREAD

**Issue by mplorentz** [ssbc/go-ssb-room#370]
I can no longer sign in to https://hermies.club with Manyverse. I think it's a problem with the hermies.club instance specifically, because I can sign into other rooms with the same copy of Manyverse. 

There are two sets of steps to reproduce. One starting on the Hermies.club website and one starting from inside Manyverse
Steps to reproduce from web:
 1. Open hermies.club website
 2. Click sign in 
 3. Click "Sign in with SSB"
 4. Click "Sign in with SSB" on the QR code page 
 5. Tap "Yes" on the "Allow sign-in" prompt in Manyverse 
 Expected: I get a success message and am forwarded back to my browser, where I am signed in. 
Actual: nothing happens in Manyverse. Switching back to the hermies.club website shows the same page as before with a "Sign in with SSB" button on it.  The hermies.club server logs the following message:
```
Jan 21 12:15:28 hermiesclub gossbroom[227805]: level=warn unit=tunnel caller=<@4RzU.ed25519> target=<@QlCT.ed25519> event="source errored" err="muxrpc: session terminated"
Jan 21 12:15:28 hermiesclub gossbroom[227805]: level=warn remote="<ip redacted>:55710|@4RzUEMr+dGtLVubYdU4LK/DOjYpjy0EaDUi06Wgk7io=.ed25519" event="consume failed" req=-8 method=tunnel.connect err="muxrpc: byte source canceled: context canceled"
Jan 21 12:15:28 hermiesclub gossbroom[227805]: level=warn remote="<ip redacted>:55710|@4RzUEMr+dGtLVubYdU4LK/DOjYpjy0EaDUi06Wgk7io=.ed25519" event="unhandled packet" reqID=1166905701 len=3066950429 flags="{FlagString, FlagJSON, FlagEndErr}"
Jan 21 12:15:28 hermiesclub gossbroom[227805]: level=warn remote="<ip redacted>:55710|@4RzUEMr+dGtLVubYdU4LK/DOjYpjy0EaDUi06Wgk7io=.ed25519" event="unhandled packet" reqID=-2127412491 len=1410634204 flags="{FlagString, FlagJSON, FlagStream, FlagEndErr}"
Jan 21 12:15:28 hermiesclub gossbroom[227805]: level=warn remote="<ip redacted>:55710|@4RzUEMr+dGtLVubYdU4LK/DOjYpjy0EaDUi06Wgk7io=.ed25519" event="unhandled packet" reqID=-1425531464 len=919168725 flags="{FlagString, FlagJSON, FlagEndErr}"
Jan 21 12:15:28 hermiesclub gossbroom[227805]: level=warn remote="<ip redacted>:55710|@4RzUEMr+dGtLVubYdU4LK/DOjYpjy0EaDUi06Wgk7io=.ed25519" event="unhandled packet" reqID=2000943104 len=1672270403 flags="{FlagString, FlagJSON, FlagStream, FlagEndErr}"
Jan 21 12:15:28 hermiesclub gossbroom[227805]: level=error remote="<ip redacted>:55710|@4RzUEMr+dGtLVubYdU4LK/DOjYpjy0EaDUi06Wgk7io=.ed25519" event=closed handleErr="muxrpc: error unpacking request: new request -526865: expected JSON flag for new call, got {}" closeErr=null
```

Steps to reproduce from Manyverse
 1. Open Manyverse 
 2. Navigate to connections screen
 3. Tap on hermies.club connection
 4. Tap "Sign into website" 
 5. Tap "Yes" on the "Allow sign-in" prompt 
 Expected: hermies.club page is opened and I am signed in. 
Actual: Sometimes nothing happens. Sometimes I get switched to the browser with this error (copied from server logs):
```
Jan 21 12:22:03 hermiesclub gossbroom[227805]: level=warn unit=tunnel caller=<@4RzU.ed25519> target=<@Sur8.ed25519> event="read failed" err="context canceled"
Jan 21 12:22:12 hermiesclub gossbroom[227805]: level=error package=web urlPath=/login event="handling error" path=/login err="ssb http auth: could not create token: transaction failed, rolling back: admindb: failed to generate a fresh token in a reasonable amount of time"
Jan 21 12:22:12 hermiesclub gossbroom[227805]: level=debug package=web event=rendered tpl=error.tmpl status=500 took=6.090175ms size=3961
```

**Comment by staltz** [comment]
Yeah there is something weird with hermies.club specifically and I haven't had the resources to debug it yet.

Actually, sometimes it does work. But most of the times it doesn't.

**Comment by decentral1se** [comment]
Random passing by idea:

> admindb: failed to generate a fresh token in a reasonable amount of time

This error message happens if tokens can't be inserted into the db so perhaps check disk space / permissions on the sqlite file?

**Comment by cryptix** [comment]
that error is thrown if it fails after trying 100 randoms new strings.

https://github.com/ssbc/go-ssb-room/blob/e86ac35c84902be1d4bde6691f92f9cd7bfbddaf/roomdb/sqlite/auth_withssb.go#L73

Looking over the code again I noticed that we only have cleanup for invites and password reset tokens. There are over 500 SIWSSB session tokens on hermies.club.

I will clean those out manually and see if I can whip up a function to do this on startup and periodically, like the others.
