### ISSUE TITLE
does this expose a ws connection for ssb-browser-core?

### ISSUE THREAD

**Issue by frankiebee** [ssbc/go-ssb-room#371]
it's a little unclear from the documentation but does this room expose a ws port/connection? I'm trying to build some browser libraries using ssb-browser-core and wondering if this room already suports that.

**Comment by decentral1se** [comment]
@frankiebee yeh that is possible afaiu but not documented, see https://github.com/ssbc/go-ssb-room/issues/180. If you get something working, it'd be great to see some docs! Not using this feature myself but perhaps @arj03 @KyleMaas might know something about it :crossed_fingers:

**Comment by arj03** [comment]
It does. See https://github.com/ssbc/go-ssb-room/blob/761a3b7244213eae80593d437b44cc00761a6084/docs/files/example-nginx.conf#L21. I have one running at: wss:between-two-worlds.dk:443~shs:Px7ZxMT4mtpqiNH+PHyao9+o0RdQ/nzU5qznf7WMNIE=.

**Comment by decentral1se** [comment]
Grand job, thanks! Maybe let's close this and leave https://github.com/ssbc/go-ssb-room/issues/180 open for documentation as the main remaining thing to solve here.
