### ISSUE TITLE
github.com/mattn/go-sqlite3 requires CGo

### ISSUE THREAD

**Issue by cryptix** [ssbc/go-ssb-room#79]
> cryptix: if the cgo based sqlite ever becomes a problem, there always is madscience: https://gitlab.com/cznic/sqlite
cryptix: o/ is a machine translated version of the C "dialect" in sqlite to pure Go. so it can be cross-compiled and used in environments where cgo is difficult or unavailable. possibly even wasm
statlz: if in wasm, would it run in the browser, but ... where would it store the data?
cryptx: not saying we need a wasm room but i disregarded sqlite before for other projects becasue cgo can be a pain
cryptix: like, if i wanted go-ssb-room on my small FreeBSD NAS, I need to compile for FreeBSD with a full C environment.. installing Go on the box isn't even enough then but also a full gcc/clang stdenv

The sqlite driver is the only CGo dependency we have, everything else can be cross-compiled.

I'm not jumping ship for the new, cgo-free version because I'm quite sure it still has some teething problems to go through but it's super impressive to see.

related links:

* https://dave.cheney.net/2016/01/18/cgo-is-not-go
* https://blog.golang.org/cgo
* https://gitlab.com/cznic/sqlite
* https://github.com/mattn/go-sqlite3

**Comment by ahdinosaur** [comment]
would folx be keen for arm64 cross-compilation? i'm keen to run butt.nz` on a Raspberry Pi. :pie:

**Comment by decentral1se** [comment]
Gitea are currently going for it in https://github.com/go-gitea/gitea/pull/20614 so I think it might be worth a look again!
